/**
 * HireWire Communications Registry
 *
 * Central store of all approved user-facing message templates.
 * Every message must have a reason. No reason = safe fallback only.
 *
 * Constitution: CLAUDE.md > lib/comms/reasons.ts > this file
 */

import type { CommsMessage } from "./types"
import { CommunicationReason } from "./reasons"

export const COMMS_REGISTRY: Record<string, CommsMessage> = {
  // ─── ACCOUNT_ACCESS ──────────────────────────────────────────
  "account.session_expired": {
    id: "account.session_expired",
    reason: CommunicationReason.ACCOUNT_ACCESS,
    domain: "account",
    audience: "user",
    intent: "Prompt user to re-authenticate after session expiry",
    channel: "toast",
    brandSurface: "auth",
    tone: "direct",
    priority: "high",
    title: "Session expired",
    body: "Your session expired. Sign in again to continue securely.",
    actionLabel: "Sign in",
    actionHref: "/login",
    requiresApproval: false,
  },
  "account.magic_link_sent": {
    id: "account.magic_link_sent",
    reason: CommunicationReason.ACCOUNT_ACCESS,
    domain: "account",
    audience: "user",
    intent: "Confirm magic link was sent",
    channel: "in_app",
    brandSurface: "auth",
    tone: "informational",
    priority: "normal",
    title: "Check your email",
    body: "We sent a sign-in link to your email. It expires in 1 hour.",
    requiresApproval: false,
  },
  "account.signup_confirmation": {
    id: "account.signup_confirmation",
    reason: CommunicationReason.ACCOUNT_ACCESS,
    domain: "account",
    audience: "user",
    intent: "Confirm account was created, prompt email verification",
    channel: "in_app",
    brandSurface: "auth",
    tone: "informational",
    priority: "normal",
    title: "Check your email",
    body: "Click the link we sent to verify your account and get started.",
    requiresApproval: false,
  },

  // ─── ONBOARDING_GUIDANCE ─────────────────────────────────────
  "onboarding.career_context_empty": {
    id: "onboarding.career_context_empty",
    reason: CommunicationReason.ONBOARDING_GUIDANCE,
    domain: "account",
    audience: "user",
    intent: "Prompt user to add career evidence before analysis can run",
    channel: "banner",
    brandSurface: "app_shell",
    tone: "direct",
    priority: "high",
    title: "Career Context is empty",
    body: "HireWire needs real career evidence to generate truthful materials. Add your experience to get started.",
    actionLabel: "Add Career Context",
    actionHref: "/evidence",
    requiresApproval: false,
  },
  "onboarding.profile_incomplete": {
    id: "onboarding.profile_incomplete",
    reason: CommunicationReason.ONBOARDING_GUIDANCE,
    domain: "account",
    audience: "user",
    intent: "Prompt user to complete their profile",
    channel: "banner",
    brandSurface: "app_shell",
    tone: "supportive",
    priority: "normal",
    title: "Complete your profile",
    body: "A complete profile improves the accuracy of every analysis and document HireWire generates.",
    actionLabel: "Update profile",
    actionHref: "/profile",
    requiresApproval: false,
  },

  // ─── JOB_PIPELINE_STATUS ─────────────────────────────────────
  "pipeline.job_analyzed": {
    id: "pipeline.job_analyzed",
    reason: CommunicationReason.JOB_PIPELINE_STATUS,
    domain: "pipeline",
    audience: "user",
    intent: "Notify user their job analysis is ready",
    channel: "toast",
    brandSurface: "app_shell",
    tone: "informational",
    priority: "normal",
    title: "Analysis ready",
    body: "Your job analysis is ready.",
    actionLabel: "View match",
    requiresApproval: false,
  },
  "pipeline.job_scrape_blocked": {
    id: "pipeline.job_scrape_blocked",
    reason: CommunicationReason.JOB_PIPELINE_STATUS,
    domain: "pipeline",
    audience: "user",
    intent: "Tell user job board blocked the fetch and prompt manual entry",
    channel: "banner",
    brandSurface: "app_shell",
    tone: "direct",
    priority: "high",
    title: "Job board blocked",
    body: "This job board blocked automated reading. Paste the job description manually to continue.",
    actionLabel: "Paste description",
    requiresApproval: false,
  },
  "pipeline.duplicate_found": {
    id: "pipeline.duplicate_found",
    reason: CommunicationReason.JOB_PIPELINE_STATUS,
    domain: "pipeline",
    audience: "user",
    intent: "Alert user a duplicate job was detected",
    channel: "modal",
    brandSurface: "app_shell",
    tone: "direct",
    priority: "normal",
    title: "Duplicate job found",
    body: "This looks like a job you already added. Do you want to continue anyway?",
    actionLabel: "Add anyway",
    requiresApproval: true,
  },

  // ─── APPLICATION_PACKAGE_STATUS ──────────────────────────────
  "package.draft_ready": {
    id: "package.draft_ready",
    reason: CommunicationReason.APPLICATION_PACKAGE_STATUS,
    domain: "application",
    audience: "user",
    intent: "Notify user their application package draft is ready for review",
    channel: "toast",
    brandSurface: "app_shell",
    tone: "informational",
    priority: "high",
    title: "Package draft ready",
    body: "Your application package draft is ready for a quick confidence check.",
    actionLabel: "Review package",
    requiresApproval: false,
  },
  "package.quick_questions_needed": {
    id: "package.quick_questions_needed",
    reason: CommunicationReason.APPLICATION_PACKAGE_STATUS,
    domain: "application",
    audience: "user",
    intent: "Prompt user to answer clarifying questions that improve the package",
    channel: "banner",
    brandSurface: "app_shell",
    tone: "supportive",
    priority: "normal",
    title: "Two quick answers needed",
    body: "Two quick answers could strengthen this package before you submit.",
    actionLabel: "Answer questions",
    requiresApproval: false,
  },
  "package.ready_to_apply": {
    id: "package.ready_to_apply",
    reason: CommunicationReason.APPLICATION_PACKAGE_STATUS,
    domain: "application",
    audience: "user",
    intent: "Confirm package passed review and is ready for final approval",
    channel: "toast",
    brandSurface: "app_shell",
    tone: "direct",
    priority: "high",
    title: "Ready to Apply",
    body: "This application package passed quality review and is ready for your final approval.",
    actionLabel: "Apply",
    requiresApproval: false,
  },

  // ─── READINESS_AND_BLOCKERS ───────────────────────────────────
  "blocker.quality_review_required": {
    id: "blocker.quality_review_required",
    reason: CommunicationReason.READINESS_AND_BLOCKERS,
    domain: "application",
    audience: "user",
    intent: "Explain package cannot move forward until quality review runs",
    channel: "banner",
    brandSurface: "app_shell",
    tone: "direct",
    priority: "high",
    title: "Quality review required",
    body: "This package needs Red Team review before it can move to Ready to Apply.",
    actionLabel: "Run review",
    requiresApproval: false,
  },
  "blocker.unsupported_claims": {
    id: "blocker.unsupported_claims",
    reason: CommunicationReason.READINESS_AND_BLOCKERS,
    domain: "application",
    audience: "user",
    intent: "Flag unsupported claims in package and request evidence",
    channel: "banner",
    brandSurface: "app_shell",
    tone: "direct",
    priority: "high",
    title: "Unsupported claims found",
    body: "Some claims need stronger evidence before this package can be approved.",
    actionLabel: "Review claims",
    requiresApproval: false,
  },

  // ─── BILLING_AND_PLAN ─────────────────────────────────────────
  "billing.limit_reached": {
    id: "billing.limit_reached",
    reason: CommunicationReason.BILLING_AND_PLAN,
    domain: "billing",
    audience: "user",
    intent: "Inform user they hit their generation limit and prompt upgrade",
    channel: "modal",
    brandSurface: "billing",
    tone: "direct",
    priority: "high",
    title: "Generation limit reached",
    body: "You reached your current plan's generation limit.",
    actionLabel: "View plans",
    actionHref: "/billing",
    requiresApproval: false,
  },
  "billing.payment_failed": {
    id: "billing.payment_failed",
    reason: CommunicationReason.BILLING_AND_PLAN,
    domain: "billing",
    audience: "user",
    intent: "Alert user their payment failed and prompt action",
    channel: "banner",
    brandSurface: "billing",
    tone: "urgent",
    priority: "critical",
    title: "Payment failed",
    body: "Your last payment did not go through. Update your payment method to keep your plan active.",
    actionLabel: "Update payment",
    actionHref: "/billing",
    requiresApproval: false,
  },

  // ─── ERROR_AND_RECOVERY ───────────────────────────────────────
  "error.unknown": {
    id: "error.unknown",
    reason: CommunicationReason.ERROR_AND_RECOVERY,
    domain: "system",
    audience: "user",
    intent: "Surface an unknown error with a recovery path",
    channel: "error_card",
    brandSurface: "error_state",
    tone: "direct",
    priority: "high",
    title: "Something went wrong",
    body: "Something unexpected happened. Try again or contact support if this continues.",
    actionLabel: "Try again",
    requiresApproval: false,
  },
  "error.ai_failed": {
    id: "error.ai_failed",
    reason: CommunicationReason.ERROR_AND_RECOVERY,
    domain: "system",
    audience: "user",
    intent: "Inform user AI generation failed and provide recovery",
    channel: "toast",
    brandSurface: "error_state",
    tone: "direct",
    priority: "high",
    title: "Generation failed",
    body: "The AI generation did not complete. Try again — your data is saved.",
    actionLabel: "Retry",
    requiresApproval: false,
  },

  // ─── DOCUMENT_AND_EXPORT ─────────────────────────────────────
  "document.export_ready": {
    id: "document.export_ready",
    reason: CommunicationReason.DOCUMENT_AND_EXPORT,
    domain: "document",
    audience: "user",
    intent: "Notify user their export is ready to download",
    channel: "toast",
    brandSurface: "app_shell",
    tone: "informational",
    priority: "normal",
    title: "Export ready",
    body: "Your resume export is ready.",
    actionLabel: "Download",
    requiresApproval: false,
  },

  // ─── SUPPORT_AND_FEEDBACK ─────────────────────────────────────
  "support.feedback_submitted": {
    id: "support.feedback_submitted",
    reason: CommunicationReason.SUPPORT_AND_FEEDBACK,
    domain: "support",
    audience: "user",
    intent: "Confirm feedback was received",
    channel: "toast",
    brandSurface: "app_shell",
    tone: "informational",
    priority: "low",
    title: "Feedback received",
    body: "Thanks. Your feedback was received.",
    requiresApproval: false,
  },

  // ─── EXTERNAL_DRAFTS_FOR_USER_APPROVAL ───────────────────────
  "external.recruiter_followup": {
    id: "external.recruiter_followup",
    reason: CommunicationReason.EXTERNAL_DRAFTS_FOR_USER_APPROVAL,
    domain: "coaching",
    audience: "user",
    intent: "Present a recruiter follow-up draft for user review before sending",
    channel: "external_draft",
    brandSurface: "external_draft",
    tone: "direct",
    priority: "normal",
    title: "Follow-up draft ready",
    body: "A follow-up draft is ready for your review. Edit it before sending.",
    actionLabel: "Review draft",
    requiresApproval: true,
  },
}

/**
 * Look up a registered message by ID.
 * Returns a safe fallback if the ID is not found.
 */
export function getCommsMessage(id: string): CommsMessage {
  const msg = COMMS_REGISTRY[id]
  if (msg) return msg

  // Safe branded fallback — never expose internal IDs to the user
  return {
    id: "error.unknown",
    reason: "ERROR_AND_RECOVERY",
    domain: "system",
    audience: "user",
    intent: "Fallback for unregistered message ID",
    channel: "error_card",
    brandSurface: "error_state",
    tone: "direct",
    priority: "normal",
    title: "Something went wrong",
    body: "Something unexpected happened. Try again or contact support.",
    actionLabel: "Try again",
    requiresApproval: false,
  }
}
