// Central registry for all communication templates and system messages

import { CommunicationMessage } from './types'

// Example registry structure
export const commsRegistry: Record<string, CommunicationMessage> = {
  // Empty state for jobs page
  'jobs.empty': {
    id: 'jobs.empty',
    reason: 'JOB_PIPELINE_STATUS',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'No jobs yet',
    body: 'This page shows all your job opportunities. Start by adding a new job to begin your pipeline.',
    actionLabel: 'Add Job',
    nextAction: '/jobs/new',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
  // Empty state for ready queue
  'readyQueue.empty': {
    id: 'readyQueue.empty',
    reason: 'APPLICATION_PACKAGE_STATUS',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'Nothing in the queue yet',
    body: 'Jobs move here once documents are generated and ready to review.',
    actionLabel: 'Add a job',
    nextAction: '/jobs',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
  // Empty state for documents/materials
  'documents.empty': {
    id: 'documents.empty',
    reason: 'DOCUMENT_AND_EXPORT',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'No documents generated yet',
    body: 'Add a job and run document generation to see your materials here.',
    actionLabel: 'Add a job',
    nextAction: '/jobs',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
  // Empty state for applications
  'applications.empty': {
    id: 'applications.empty',
    reason: 'APPLICATION_ACTIONS',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'No applications yet',
    body: 'Track every application you have submitted. Apply to a job to see it here.',
    actionLabel: 'Go to jobs',
    nextAction: '/jobs',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
  // Empty state for analytics
  'analytics.empty': {
    id: 'analytics.empty',
    reason: 'SYSTEM_AND_PRODUCT_UPDATES',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'No analytics yet',
    body: 'Analytics will appear here as you add jobs and generate documents.',
    actionLabel: 'Add a job',
    nextAction: '/jobs',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
  // Empty state for logs/activity
  'logs.empty': {
    id: 'logs.empty',
    reason: 'SYSTEM_AND_PRODUCT_UPDATES',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'No activity yet',
    body: 'Events will appear here as you analyze jobs and generate documents.',
    actionLabel: 'Add a job',
    nextAction: '/jobs',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
  // Empty state for materials/career context (example)
  'careerContext.empty': {
    id: 'careerContext.empty',
    reason: 'ONBOARDING_GUIDANCE',
    domain: 'PRODUCT_UI',
    audience: 'USER',
    intent: 'INFORM',
    channel: 'in_app',
    tone: 'calm',
    priority: 'normal',
    brandSurface: 'app_shell',
    subject: 'No career context yet',
    body: 'Import your experience, skills, and achievements to build your Career Context.',
    actionLabel: 'Add experience',
    nextAction: '/career-context',
    requiresApproval: false,
    isDraft: false,
    createdAt: new Date().toISOString(),
  },
}
